export const services = [
  {
    slug: "rua-ngoai-that",
    name: "Rửa ngoại thất",
    category: "Rửa ngoại thất",
    description: "Rửa sạch bùn đất, bụi bẩn, đánh bóng thân xe bằng quy trình an toàn cho lớp sơn.",
    price: "Từ 80.000đ",
    duration: "25 phút",
    badge: "Phổ biến",
    badgeTone: "text-primary",
    image: "/images/home/03_services/photos/service_exterior_wash.png",
  },
  {
    slug: "ve-sinh-noi-that",
    name: "Vệ sinh nội thất",
    category: "Vệ sinh nội thất",
    description: "Làm sạch ghế, thảm, taplo và khử mùi để khoang nội thất luôn thoáng sạch.",
    price: "Từ 150.000đ",
    duration: "45 phút",
    badge: "Chuyên sâu",
    badgeTone: "text-accent-violet",
    image: "/images/home/03_services/photos/service_interior_cleaning.png",
  },
  {
    slug: "cham-soc-toan-dien",
    name: "Chăm sóc toàn diện",
    category: "Chăm sóc toàn diện",
    description: "Rửa xe, vệ sinh nội thất, đánh bóng và bảo dưỡng trong một quy trình đồng bộ.",
    price: "Từ 280.000đ",
    duration: "75 phút",
    badge: "Cao cấp",
    badgeTone: "text-tier-gold-ink",
    image: "/images/home/03_services/photos/service_full_detailing.png",
  },
  {
    slug: "phu-bong-bao-duong",
    name: "Phủ bóng và bảo dưỡng",
    category: "Phủ bóng",
    description: "Phủ ceramic/bóng nano chuyên dụng, bảo vệ lớp sơn xe bền đẹp lâu dài.",
    price: "Từ 350.000đ",
    duration: "90 phút",
    badge: "Bảo vệ sơn",
    badgeTone: "text-success",
    image: "/images/home/03_services/photos/service_paint_protection.png",
  },
  {
    slug: "ve-sinh-khoang-may",
    name: "Vệ sinh khoang máy",
    category: "Vệ sinh khoang máy",
    description: "Làm sạch khoang máy an toàn và chuyên sâu, bảo vệ các chi tiết điện.",
    price: "Từ 220.000đ",
    duration: "60 phút",
    badge: "Kỹ thuật",
    badgeTone: "text-no-show",
    image: "/images/home/03_services/photos/service_engine_cleaning.png",
  },
  {
    slug: "rua-nhanh-express",
    name: "Rửa nhanh Express",
    category: "Rửa nhanh",
    description: "Rửa nhanh ngoại thất, sạch ngay trong thời gian ngắn — phù hợp khi bạn cần xe gấp.",
    price: "Từ 60.000đ",
    duration: "15 phút",
    badge: "Tiện lợi",
    badgeTone: "text-accent-cyan",
    image: "/images/home/03_services/photos/service_express_wash.png",
  },
];

export const serviceCategories = [
  "Tất cả",
  "Rửa ngoại thất",
  "Vệ sinh nội thất",
  "Chăm sóc toàn diện",
  "Phủ bóng",
  "Vệ sinh khoang máy",
  "Rửa nhanh",
];

export const plans = [
  {
    name: "Gói Cơ Bản",
    tagline: "Phù hợp cho việc rửa xe định kỳ",
    price: "80.000đ",
    duration: "25 phút",
    features: ["Rửa ngoại thất", "Hút bụi nội thất", "Lau khô thân xe", "Vệ sinh kính"],
  },
  {
    name: "Gói Tiêu Chuẩn",
    tagline: "Lựa chọn cân bằng cho xe của bạn",
    price: "180.000đ",
    duration: "50 phút",
    features: ["Rửa ngoại thất chuyên sâu", "Vệ sinh nội thất toàn diện", "Hút bụi & khử mùi", "Lau khô thân xe", "Vệ sinh kính & gương"],
  },
  {
    name: "Gói Cao Cấp",
    tagline: "Trải nghiệm chăm sóc xe toàn diện",
    price: "320.000đ",
    duration: "90 phút",
    featured: true,
    badge: "Được yêu thích",
    features: ["Rửa ngoại thất cao cấp", "Vệ sinh nội thất chuyên sâu", "Hút bụi, khử mùi diệt khuẩn", "Đánh bóng & bảo vệ sơn", "Vệ sinh kính, gương, lốp", "Sấy khô & hoàn thiện"],
  },
];

export const tiers = [
  {
    name: "Đồng",
    perk: "Ưu tiên kiểm tra xe",
    condition: "Từ 0 điểm",
    discount: "Giảm 5%",
    badge: "/badges/dong.png",
    medal: "/images/home/04_membership/medals/medal_dong.png?v=4",
    color: "var(--tier-bronze)",
    pedestal: "from-tier-bronze-ink to-foreground",
    benefits: ["Tích điểm sau mỗi lần rửa", "Ưu đãi chào mừng", "Nhắc lịch chăm sóc xe"],
  },
  {
    name: "Bạc",
    perk: "Tặng 1 lượt rửa xe cơ bản",
    condition: "Từ 500 điểm",
    discount: "Giảm 8%",
    badge: "/badges/bac.png",
    medal: "/images/home/04_membership/medals/medal_bac.png?v=4",
    color: "var(--tier-silver)",
    pedestal: "from-tier-silver-ink to-foreground",
    benefits: ["Toàn bộ quyền lợi hạng Đồng", "Ưu tiên đặt lịch", "Quà tặng sinh nhật"],
  },
  {
    name: "Vàng",
    perk: "Miễn phí hút bụi",
    condition: "Từ 1.500 điểm",
    discount: "Giảm 12%",
    badge: "/badges/vang.png",
    medal: "/images/home/04_membership/medals/medal_vang.png?v=4",
    color: "var(--tier-gold)",
    pedestal: "from-tier-gold-ink to-foreground",
    benefits: ["Toàn bộ quyền lợi hạng Bạc", "Tích điểm nhân đôi", "Ưu đãi hàng tháng"],
  },
  {
    name: "Bạch Kim",
    perk: "Tặng 1 lượt phủ nano nhanh",
    condition: "Từ 3.500 điểm",
    discount: "Giảm 15%",
    badge: "/badges/bach-kim.png",
    medal: "/images/home/04_membership/medals/medal_bach_kim.png?v=4",
    color: "var(--tier-platinum)",
    pedestal: "from-tier-platinum to-foreground",
    benefits: ["Toàn bộ quyền lợi hạng Vàng", "Ưu tiên tại gara", "Hỗ trợ chuyên biệt"],
  },
  {
    name: "Kim Cương",
    perk: "Ưu tiên phục vụ",
    condition: "Từ 8.000 điểm",
    discount: "Giảm 20%",
    badge: "/badges/kim-cuong.png",
    medal: "/images/home/04_membership/medals/medal_kim_cuong.png?v=4",
    color: "var(--tier-diamond)",
    pedestal: "from-tier-diamond to-foreground",
    benefits: ["Toàn bộ quyền lợi hạng Bạch Kim", "Chăm sóc riêng", "Đặc quyền sự kiện"],
  },
];

export const steps = [
  { title: "Chọn xe & dịch vụ", description: "Thêm xe và chọn gói chăm sóc phù hợp." },
  { title: "Chọn gara & khung giờ", description: "Tìm gara gần bạn và thời gian thuận tiện." },
  { title: "Check-in tại gara", description: "Đến gara và check-in bằng mã đặt lịch." },
  { title: "Theo dõi quá trình", description: "Biết xe đang ở trạng thái nào trong thời gian thực." },
  { title: "Thanh toán & nhận điểm", description: "Hoàn tất dịch vụ, nhận hóa đơn và cộng điểm tự động." },
];

export const testimonials = [
  { name: "Trần Minh Anh", avatar: "/images/home/07_testimonials/avatar_minh_anh.png", rating: 5, content: "Đặt lịch chỉ trong một phút, xe sạch bóng và còn được tích điểm. Trải nghiệm rất chuyên nghiệp.", service: "Chăm sóc toàn diện" },
  { name: "Phạm Thảo Linh", avatar: "/images/home/07_testimonials/avatar_thao_linh.png", rating: 5, content: "Mình theo dõi được tiến độ ngay trên điện thoại nên chủ động thời gian hơn rất nhiều.", service: "Vệ sinh nội thất" },
  { name: "Lê Hoàng Nam", avatar: "/images/home/07_testimonials/avatar_hoang_nam.png", rating: 5, content: "Dịch vụ phủ bóng rất ấn tượng, chi phí rõ ràng và nhân viên đúng giờ.", service: "Phủ bóng và bảo dưỡng" },
];
