import { ArrowRight, CheckCircle2 } from "lucide-react";
import { Link } from "react-router-dom";
import { formatDate } from "@/lib/booking-flow";

export function BookingSuccessStep({ result, selection }) {
  const primaryPath = result.paymentId ? "/khach-hang/thanh-toan" : "/khach-hang/lich-dat";
  const primaryLabel = result.paymentId
      ? "Tiếp tục thanh toán"
      : "Xem chi tiết lịch đặt";
  return <div className="mx-auto max-w-3xl rounded-[2rem] border border-border bg-card p-6 text-center shadow-sm sm:p-10"><span className="mx-auto grid size-16 place-items-center rounded-3xl bg-emerald-100 text-emerald-600"><CheckCircle2 size={34} /></span>{result.isDemo && <span className="mt-5 inline-flex rounded-full bg-secondary px-3 py-1 text-xs font-extrabold text-secondary-foreground">Dữ liệu mẫu</span>}<h2 className="mt-6 text-2xl font-extrabold text-foreground sm:text-3xl">Đã tạo lịch đặt thành công</h2><p className="mx-auto mt-3 max-w-xl leading-7 text-muted-foreground">Lịch đặt của bạn đang ở trạng thái Chờ thanh toán. Vui lòng hoàn tất thanh toán để xác nhận lịch.</p><span className="mt-5 inline-flex rounded-full bg-amber-100 px-4 py-2 text-sm font-extrabold text-amber-700">Chờ thanh toán</span>{result.isDemo && <p className="mx-auto mt-4 max-w-xl rounded-2xl bg-secondary px-4 py-3 text-sm text-secondary-foreground">Dữ liệu này dùng để demo giao diện. API thật sẽ được kết nối sau.</p>}<dl className="mt-8 grid gap-4 rounded-3xl bg-muted p-5 text-left sm:grid-cols-2">{[["Mã booking", result.bookingCode || result.bookingId || "Đang cập nhật"],["Xe", selection.vehicle.licensePlate],["Dịch vụ", selection.service.name],["Gara", selection.garage.name],["Ngày giờ", `${formatDate(selection.date)}, ${selection.slot.startTime}`],["Trạng thái", "Chờ thanh toán"]].map(([label, value]) => <div key={label}><dt className="text-xs font-semibold text-muted-foreground">{label}</dt><dd className="mt-1 font-bold text-foreground">{value}</dd></div>)}</dl><div className="mt-8 flex flex-col justify-center gap-3 sm:flex-row"><Link to={primaryPath} className="inline-flex items-center justify-center gap-2 rounded-2xl bg-primary px-6 py-3 font-bold text-primary-foreground">{primaryLabel}<ArrowRight size={18} /></Link><Link to="/khach-hang" className="rounded-2xl border border-border px-6 py-3 font-bold text-foreground">Về trang khách hàng</Link></div></div>;
}
