import { CalendarDays, Clock3 } from "lucide-react";
import { nextDates } from "@/lib/booking-flow";
import { cn } from "@/lib/utils";
import { getOperationStatusLabel } from "@/lib/status-labels";

export function SlotStep({ date, onDateChange, slots, selectedId, onSelect, loading }) {
  const dates = nextDates();
  return <div className="space-y-6"><section className="rounded-3xl border border-[var(--border-soft)] bg-white p-5 shadow-sm"><h2 className="flex items-center gap-2 text-lg font-extrabold"><CalendarDays className="text-[var(--brand-blue)]" /> Chọn ngày</h2><div className="mt-5 grid grid-cols-4 gap-2 sm:grid-cols-7">{dates.map((item) => <button key={item.value} type="button" onClick={() => onDateChange(item.value)} className={cn("rounded-2xl border px-2 py-3 text-center transition", date === item.value ? "border-[var(--brand-blue)] bg-[var(--brand-blue)] text-white" : "border-[var(--border-soft)] bg-[var(--bg-main)] hover:border-[var(--brand-blue)]")}><span className="block text-[10px] font-bold">{item.weekday}</span><strong className="mt-1 block text-lg">{item.day}</strong></button>)}</div></section><section className="rounded-3xl border border-[var(--border-soft)] bg-white p-5 shadow-sm"><h2 className="flex items-center gap-2 text-lg font-extrabold"><Clock3 className="text-[var(--brand-blue)]" /> Khung giờ phù hợp</h2>{loading ? <p className="py-12 text-center text-sm text-[var(--text-muted)]">Đang tải dữ liệu...</p> : !slots.length ? <p className="py-12 text-center text-sm text-[var(--text-muted)]">Không có khung giờ phù hợp trong ngày này.</p> : <div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{slots.map((slot) => {
    const selected = String(selectedId) === String(slot.id);
    return <button key={slot.id} type="button" disabled={slot.disabled} onClick={() => onSelect(slot)} className={cn("rounded-2xl border-2 p-4 text-left transition", selected && "border-[var(--brand-blue)] bg-[var(--brand-blue)] text-white", !selected && !slot.disabled && "border-[var(--border-soft)] hover:border-[var(--brand-blue)]", slot.disabled && "cursor-not-allowed border-slate-200 bg-slate-100 opacity-55")}><div className="flex items-center justify-between gap-3"><strong>{slot.startTime} - {slot.endTime || "..."}</strong><span className={cn("rounded-full px-2.5 py-1 text-[10px] font-bold", selected ? "bg-white/20 text-white" : slot.status === "OPEN" && !slot.disabled ? "bg-emerald-50 text-emerald-700" : "bg-slate-200 text-slate-600")}>{getOperationStatusLabel(slot.disabled && slot.status === "OPEN" ? "FULL" : slot.status)}</span></div><p className={cn("mt-3 text-xs", selected ? "text-white/80" : "text-[var(--text-muted)]")}>Đã đặt {slot.bookedCount}/{slot.maxCapacity} chỗ</p></button>;
  })}</div>}</section></div>;
}
